version: '3'
services:
  mongodb-server:
    image: mongo:6.0.3
    restart: always
    volumes:
      - ./mongoData:/data/db
    ports:
      - 27016:27017
  node-app:
    image: lembutt/itmo-docker-task-7:latest
    ports:
      - 33722:8080
    depends_on:
      - mongodb-server